"""Gate 5 缺口：真实 sequence 修复 + backup/restore 演练。

补上 `import_reconcile_probe.py` 的两处未覆盖：

1. **sequence 修复**：初版用 plain `int` 主键，`setval` 路径从未执行。
   本脚本用 `GENERATED ... AS IDENTITY`（PostgreSQL 惯用）建表，导入保留原 ID 后
   **必须 `setval`/`RESTART`**，否则下一次插入会撞已有 ID。用负向用例证明：
   不修复 → 冲突；修复后 → 可继续插入。
2. **backup/restore 演练**：`pg_dump` → 新库 `pg_restore` → 逐表对账 +
   关键约束/序列状态验证。

用法（需要两个隔离库：源与目标）：

    PGTEST_DSN=... PGTEST_DSN_RESTORE=... python3 scripts/migration-proof/import_sequence_probe.py
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile

DDL = """
DROP TABLE IF EXISTS sq_items CASCADE;
CREATE TABLE sq_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);
"""


def _conn(dsn: str):
    import psycopg
    return psycopg.connect(dsn)


def test_sequence_repair(dsn: str, failures: list[str]) -> None:
    """导入保留原 ID 后必须修复 sequence，否则新插入撞主键。"""
    import psycopg
    with _conn(dsn) as c:
        c.execute(DDL)
        c.commit()
        # 模拟「导入保留原 ID」：显式插入 1..5（IDENTITY 允许 BY DEFAULT 显式值）
        with c.cursor() as cur:
            cur.executemany("INSERT INTO sq_items (id, name) VALUES (%s,%s)",
                            [(i, f"row{i}") for i in range(1, 6)])
        c.commit()

        # 负向：不修复 sequence，新插入必须冲突
        conflict = False
        try:
            c.execute("INSERT INTO sq_items (name) VALUES ('new')")
            c.commit()
        except psycopg.errors.UniqueViolation:
            c.rollback()
            conflict = True
        print(f"  [{'OK ' if conflict else 'BAD'}] 不修复 sequence -> "
              f"{'主键冲突（符合预期）' if conflict else '竟然插入成功'}")
        if not conflict:
            failures.append("不修复 sequence 时未冲突——用例未证明 setval 的必要性")

        # 修复：把 identity sequence 推到 max(id)
        c.execute("SELECT setval(pg_get_serial_sequence('sq_items','id'),"
                  " (SELECT max(id) FROM sq_items))")
        c.commit()

        # 正向：修复后可继续插入
        try:
            c.execute("INSERT INTO sq_items (name) VALUES ('after-repair')")
            c.commit()
            new_id = c.execute("SELECT max(id) FROM sq_items").fetchone()[0]
            ok = new_id == 6
            print(f"  [{'OK ' if ok else 'BAD'}] 修复 sequence 后插入 -> 新 id={new_id}（期望 6）")
            if not ok:
                failures.append(f"修复后新 id 应为 6，实际 {new_id}")
        except Exception as exc:  # noqa: BLE001
            c.rollback()
            print(f"  [BAD] 修复 sequence 后仍失败：{type(exc).__name__}")
            failures.append("修复 sequence 后仍无法插入")


def test_backup_restore(dsn: str, failures: list[str]) -> None:
    """pg_dump → pg_restore → 对账。缺少 pg_dump/pg_restore 时明确记录为环境阻塞。"""
    if not shutil.which("pg_dump") or not shutil.which("pg_restore"):
        print("  SKIP: pg_dump/pg_restore 不在 PATH（环境阻塞，不是通过）")
        return
    restore_dsn = os.environ.get("PGTEST_DSN_RESTORE")
    if not restore_dsn:
        print("  SKIP: 需要 PGTEST_DSN_RESTORE 指向第二个隔离库")
        return

    with tempfile.TemporaryDirectory(prefix="fg-restore-") as tmp:
        dump = os.path.join(tmp, "dump.sql")
        env = {**os.environ}
        # pg_dump 需要 libpq 风格 DSN；psycopg 的 DSN 通常兼容
        src = dsn.replace("postgresql+psycopg://", "postgresql://")
        dst = restore_dsn.replace("postgresql+psycopg://", "postgresql://")
        r = subprocess.run(["pg_dump", "--clean", "--if-exists", "-f", dump, src],
                           capture_output=True, text=True, timeout=120, env=env)
        if r.returncode != 0:
            print(f"  BAD: pg_dump 失败：{r.stderr.strip()[:160]}")
            failures.append("pg_dump 失败")
            return
        print(f"  OK  pg_dump -> {os.path.getsize(dump)} bytes")

        r = subprocess.run(["psql", "-q", "-f", dump, dst],
                           capture_output=True, text=True, timeout=120, env=env)
        if r.returncode != 0:
            print(f"  BAD: restore 失败：{r.stderr.strip()[:160]}")
            failures.append("pg_restore/psql 恢复失败")
            return
        print("  OK  restore 完成")

        # 对账：行数与最大 id
        with _conn(dsn) as a, _conn(restore_dsn) as b:
            na = a.execute("SELECT count(*), max(id) FROM sq_items").fetchone()
            nb = b.execute("SELECT count(*), max(id) FROM sq_items").fetchone()
        ok = na == nb
        print(f"  [{'OK ' if ok else 'BAD'}] 恢复后对账 -> 源 {na} / 目标 {nb}")
        if not ok:
            failures.append(f"恢复后对账不一致：源 {na} 目标 {nb}")


def main() -> int:
    try:
        import psycopg  # noqa: F401
    except ImportError:
        print("SKIP: psycopg 未安装")
        return 2
    dsn = os.environ.get("PGTEST_DSN")
    if not dsn:
        print("SKIP: 需要 PGTEST_DSN 指向隔离 PostgreSQL（不得指向开发库/线上）")
        return 2

    failures: list[str] = []
    print("sequence 修复：")
    test_sequence_repair(dsn, failures)
    print("backup/restore：")
    test_backup_restore(dsn, failures)

    with _conn(dsn) as c:
        c.execute("DROP TABLE IF EXISTS sq_items CASCADE")
        c.commit()

    if failures:
        print("FAIL:")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("PASS: sequence 修复必要性已证明；backup/restore 已演练")
    return 0


if __name__ == "__main__":
    sys.exit(main())
